"""Shutdown cleanup planning."""

from __future__ import annotations

from live_demo_api.orchestration.orchestration_types import SessionResource

CLEANUP_ORDER = (
    "voice_session",
    "browser_session",
    "learner_run",
    "transport_session",
    "redis_live_state",
    "object_artifact",
)


def ordered_cleanup_resources(
    resources: tuple[SessionResource, ...],
) -> tuple[SessionResource, ...]:
    order = {resource_type: index for index, resource_type in enumerate(CLEANUP_ORDER)}
    return tuple(
        sorted(
            resources,
            key=lambda item: (
                order.get(item.resource_type, len(CLEANUP_ORDER)),
                item.resource_type,
                item.resource_id,
            ),
        )
    )


def deterministic_summary_payload(
    *, session_id: object, transcript_event_count: int = 0, browser_action_count: int = 0
) -> dict[str, object]:
    return {
        "session_id": str(session_id),
        "status": "completed",
        "duration_seconds": 0,
        "transcript_event_count": transcript_event_count,
        "browser_action_count": browser_action_count,
        "features_shown": [],
        "questions_detected": [],
        "summary_type": "deterministic_phase_12",
        "message": (
            "Detailed AI lead summary will be generated by the post-demo intelligence phase."
        ),
    }
