#!/usr/bin/env python3
"""Generate docs/README.md from the current documentation tree."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"

SECTIONS: list[tuple[str, str]] = [
    ("Setup", "setup"),
    ("Architecture", "architecture"),
    ("Providers", "providers"),
    ("Recipes", "recipes"),
    ("Demo", "demo"),
    ("Troubleshooting", "troubleshooting"),
    ("Runbooks", "runbooks"),
    ("Development", "development"),
    ("Flows", "flows"),
    ("Operations", "operations"),
]


def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").title()


def main() -> int:
    lines: list[str] = [
        "# Documentation Hub",
        "",
        "This index is generated by `scripts/docs/generate_docs_index.py`.",
        "",
        "## Audience Map",
        "",
        "| Audience | Start here |",
        "| --- | --- |",
        "| New local developer | [setup/local-setup.md](setup/local-setup.md) |",
        "| Staff/system-design reviewer | [architecture/system-design.md](architecture/system-design.md) |",
        "| Interviewer or demo reviewer | [demo/interview-demo-script.md](demo/interview-demo-script.md) |",
        "| Maintainer debugging issues | [troubleshooting/troubleshooting.md](troubleshooting/troubleshooting.md) |",
        "",
        "## Capability Map",
        "",
        "```mermaid",
        "mindmap",
        "  root((Live Demo Agent Docs))",
        "    Setup",
        "      Local free mode",
        "      Docker Compose profiles",
        "      Provider modes",
        "    Architecture",
        "      Services",
        "      Data flow",
        "      Agent flow",
        "      Browser flow",
        "      Safety",
        "      Observability",
        "    Demo",
        "      Interview script",
        "      Expected events",
        "      Fallbacks",
        "    Operations",
        "      Troubleshooting",
        "      Runbooks",
        "      Deployment",
        "```",
        "",
        "## Documents",
        "",
    ]

    for section_title, directory in SECTIONS:
        section_dir = DOCS / directory
        if not section_dir.exists():
            continue
        lines.extend([f"### {section_title}", ""])
        for path in sorted(section_dir.glob("*.md")):
            rel = path.relative_to(DOCS)
            lines.append(f"- [{title_for(path)}]({rel.as_posix()})")
        lines.append("")

    lines.extend(
        [
            "## Root Links",
            "",
            "- [Root README](../README.md)",
            "- [Architecture foundation](../architecture/README.md)",
            "- [Contracts package](../packages/contracts/README.md)",
            "- [Policy package](../packages/policies/README.md)",
            "",
        ]
    )

    (DOCS / "README.md").write_text("\n".join(lines), encoding="utf-8")
    print("Generated docs/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
