apiVersion: v1
kind: ResourceQuota
metadata:
  name: live-demo-agent-quota
spec:
  hard:
    pods: "80"
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "120"
    limits.memory: 240Gi
