"""Standard structured log event names."""

HTTP_REQUEST_STARTED = "http.request.started"
HTTP_REQUEST_COMPLETED = "http.request.completed"
HTTP_REQUEST_FAILED = "http.request.failed"
SESSION_CREATED = "session.created"
SESSION_PREWARMING_STARTED = "session.prewarming.started"
SESSION_PREWARMING_COMPLETED = "session.prewarming.completed"
SESSION_LIVE_STARTED = "session.live.started"
SESSION_RECOVERY_STARTED = "session.recovery.started"
SESSION_SHUTDOWN_STARTED = "session.shutdown.started"
SESSION_SHUTDOWN_COMPLETED = "session.shutdown.completed"
TURN_STARTED = "turn.started"
TURN_COMPLETED = "turn.completed"
TURN_FAILED = "turn.failed"
TURN_INTERRUPTED = "turn.interrupted"
VOICE_STT_PARTIAL = "voice.stt.partial"
VOICE_STT_FINAL = "voice.stt.final"
VOICE_TTS_STARTED = "voice.tts.started"
VOICE_TTS_FIRST_AUDIO = "voice.tts.first_audio"
VOICE_TTS_COMPLETED = "voice.tts.completed"
VOICE_INTERRUPTION_DETECTED = "voice.interruption.detected"
LLM_REQUEST_STARTED = "llm.request.started"
LLM_REQUEST_COMPLETED = "llm.request.completed"
LLM_REQUEST_FAILED = "llm.request.failed"
BROWSER_ACTION_STARTED = "browser.action.started"
BROWSER_ACTION_COMPLETED = "browser.action.completed"
BROWSER_ACTION_FAILED = "browser.action.failed"
BROWSER_SCREEN_UPDATED = "browser.screen.updated"
POLICY_EVALUATED = "policy.evaluated"
POLICY_BLOCKED = "policy.blocked"
LEARNER_JOB_STARTED = "learner.job.started"
LEARNER_JOB_COMPLETED = "learner.job.completed"
LEARNER_JOB_FAILED = "learner.job.failed"
POST_DEMO_JOB_STARTED = "post_demo.job.started"
POST_DEMO_JOB_COMPLETED = "post_demo.job.completed"
POST_DEMO_JOB_FAILED = "post_demo.job.failed"
CRM_EXPORT_STARTED = "crm.export.started"
CRM_EXPORT_COMPLETED = "crm.export.completed"
CRM_EXPORT_FAILED = "crm.export.failed"
LATENCY_BUDGET_VIOLATION = "latency_budget.violation"
SECURITY_REDACTION_APPLIED = "security.redaction.applied"

ALL_LOG_EVENTS = frozenset(
    value for key, value in globals().items() if key.isupper() and isinstance(value, str)
)
