"""Shared semantic attributes for spans and logs."""

SERVICE_NAME = "service.name"
DEPLOYMENT_ENVIRONMENT = "deployment.environment"
ORGANIZATION_ID = "live_demo.organization_id"
SESSION_ID = "live_demo.session_id"
PRODUCT_ID = "live_demo.product_id"
TURN_ID = "live_demo.turn_id"
VOICE_SESSION_ID = "live_demo.voice_session_id"
BROWSER_SESSION_ID = "live_demo.browser_session_id"
COMMAND_ID = "live_demo.command_id"
ACTION_ID = "live_demo.action_id"
SCREEN_ID = "live_demo.screen_id"
RECIPE_ID = "live_demo.recipe_id"
PHASE = "live_demo.phase"
OPERATION = "live_demo.operation"
SUCCESS = "live_demo.success"
ERROR_CODE = "live_demo.error_code"
RISK_LEVEL = "live_demo.risk_level"
POLICY_DECISION = "live_demo.policy_decision"
PROVIDER = "live_demo.provider"
MODEL = "live_demo.model"
TRANSPORT_PROVIDER = "live_demo.transport_provider"
