"""Canonical span names for all services."""

SESSION_CREATE = "session.create"
SESSION_PREWARM = "session.prewarm"
SESSION_PREWARM_COMPILE_RECIPE = "session.prewarm.compile_recipe"
SESSION_PREWARM_CREATE_BROWSER = "session.prewarm.create_browser"
SESSION_PREWARM_NAVIGATE_BROWSER = "session.prewarm.navigate_browser"
SESSION_PREWARM_READ_FIRST_SCREEN = "session.prewarm.read_first_screen"
SESSION_PREWARM_CREATE_VOICE_SESSION = "session.prewarm.create_voice_session"
SESSION_PREWARM_WARM_PROVIDER = "session.prewarm.warm_provider"
SESSION_PREWARM_ENQUEUE_LEARNER = "session.prewarm.enqueue_learner"
SESSION_START_LIVE = "session.start_live"
SESSION_SHUTDOWN = "session.shutdown"
SESSION_RECOVERY = "session.recovery"

TURN_PROCESS = "turn.process"
TURN_CONTEXT_BUILD = "turn.context_build"
TURN_LLM_REQUEST = "turn.llm_request"
TURN_OUTPUT_VALIDATE = "turn.output_validate"
TURN_TTS_START = "turn.tts_start"
TURN_FIRST_AUDIO = "turn.first_audio"
TURN_TOOL_ROUTE = "turn.tool_route"
TURN_MEMORY_UPDATE = "turn.memory_update"
TURN_INTERRUPTION = "turn.interruption"

VOICE_AUDIO_IN = "voice.audio_in"
VOICE_VAD_SPEECH_START = "voice.vad_speech_start"
VOICE_TURN_DETECT = "voice.turn_detect"
VOICE_STT_STREAM = "voice.stt_stream"
VOICE_STT_PARTIAL = "voice.stt_partial"
VOICE_STT_FINAL = "voice.stt_final"
VOICE_TTS_REQUEST = "voice.tts_request"
VOICE_TTS_FIRST_AUDIO = "voice.tts_first_audio"
VOICE_TTS_STREAM = "voice.tts_stream"
VOICE_AUDIO_OUT = "voice.audio_out"
VOICE_INTERRUPT_STOP_TTS = "voice.interrupt_stop_tts"

BROWSER_SESSION_CREATE = "browser.session.create"
BROWSER_NAVIGATE = "browser.navigate"
BROWSER_READ_SCREEN = "browser.read_screen"
BROWSER_EXTRACT_VISIBLE_TEXT = "browser.extract_visible_text"
BROWSER_EXTRACT_DOM_SUMMARY = "browser.extract_dom_summary"
BROWSER_EXTRACT_ACCESSIBILITY = "browser.extract_accessibility"
BROWSER_EXTRACT_ELEMENTS = "browser.extract_elements"
BROWSER_CAPTURE_SCREENSHOT = "browser.capture_screenshot"
BROWSER_STORE_SCREENSHOT = "browser.store_screenshot"
BROWSER_ACTION_VALIDATE = "browser.action.validate"
BROWSER_ACTION_EXECUTE = "browser.action.execute"
BROWSER_ACTION_OBSERVE = "browser.action.observe"
BROWSER_ACTION_CLICK = "browser.action.click"
BROWSER_ACTION_TYPE = "browser.action.type"
BROWSER_ACTION_SCROLL = "browser.action.scroll"
BROWSER_ACTION_GO_BACK = "browser.action.go_back"
BROWSER_CURSOR_EMIT = "browser.cursor.emit"

LEARNER_JOB_PROCESS = "learner.job.process"
LEARNER_FIRST_SCREEN_SUMMARY = "learner.first_screen_summary"
LEARNER_CATEGORY_DETECT = "learner.category_detect"
LEARNER_ACTION_EXPLORE = "learner.action_explore"
LEARNER_DEMO_GRAPH_UPDATE = "learner.demo_graph_update"
LEARNER_SCREEN_MATCH = "learner.screen_match"
LEARNER_ROUTE_GENERATE = "learner.route_generate"
LEARNER_KNOWLEDGE_CHUNK = "learner.knowledge_chunk"
LEARNER_EMBEDDING_WRITE = "learner.embedding_write"
LEARNER_RETRIEVAL = "learner.retrieval"

POST_DEMO_JOB_PROCESS = "post_demo.job.process"
POST_DEMO_EVIDENCE_LOAD = "post_demo.evidence_load"
POST_DEMO_FEATURE_TRACK = "post_demo.feature_track"
POST_DEMO_INSIGHT_EXTRACT = "post_demo.insight_extract"
POST_DEMO_SUMMARY_GENERATE = "post_demo.summary_generate"
POST_DEMO_CRM_MAP_PAYLOAD = "post_demo.crm_map_payload"
POST_DEMO_CRM_EXPORT = "post_demo.crm_export"

POLICY_ACTION_EVALUATE = "policy.action.evaluate"
POLICY_RECIPE_EVALUATE = "policy.recipe.evaluate"
POLICY_RBAC_CHECK = "policy.rbac.check"
POLICY_REDACTION_APPLY = "policy.redaction.apply"
POLICY_AUDIT_WRITE = "policy.audit.write"

ALL_SPAN_NAMES = frozenset(
    name for name, value in globals().items() if name.isupper() and isinstance(value, str)
)
