#!/usr/bin/env python3
"""Allocate stable local host ports for Docker Compose.

The first run prefers familiar ports, but falls forward to free ports when a
developer already has something bound locally. The generated file is reused on
later runs so `make up` does not churn URLs while the stack is running.
"""

from __future__ import annotations

import argparse
import socket
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / ".local/runtime"
OUT_FILE = OUT_DIR / "ports.env"
ENV_FILE = ROOT / ".env"

PORTS: dict[str, int] = {
    "HOST_WEB_PORT": 3000,
    "HOST_API_PORT": 8000,
    "HOST_BROWSER_RUNTIME_PORT": 8200,
    "HOST_AGENT_RUNTIME_PORT": 8300,
    "HOST_POSTGRES_PORT": 5432,
    "HOST_REDIS_PORT": 6379,
    "HOST_MINIO_API_PORT": 9000,
    "HOST_MINIO_CONSOLE_PORT": 9001,
    "HOST_TTS_PORT": 8100,
    "HOST_OLLAMA_PORT": 11434,
    "HOST_OTEL_GRPC_PORT": 4317,
    "HOST_OTEL_HTTP_PORT": 4318,
    "HOST_PROMETHEUS_PORT": 9090,
    "HOST_GRAFANA_PORT": 3001,
    "HOST_LOKI_PORT": 3100,
    "HOST_JAEGER_UI_PORT": 16686,
    "HOST_JAEGER_COLLECTOR_PORT": 14268,
}


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def port_is_free(port: int) -> bool:
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.2):
            return False
    except OSError:
        pass
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


def pick_port(preferred: int, allocated: set[int]) -> int:
    if preferred not in allocated and port_is_free(preferred):
        allocated.add(preferred)
        return preferred
    start = max(1024, preferred + 1)
    for port in range(start, 65535):
        if port not in allocated and port_is_free(port):
            allocated.add(port)
            return port
    raise RuntimeError("No free local TCP ports are available.")


def render(values: dict[str, str]) -> str:
    web = values["HOST_WEB_PORT"]
    api = values["HOST_API_PORT"]
    browser = values["HOST_BROWSER_RUNTIME_PORT"]
    agent = values["HOST_AGENT_RUNTIME_PORT"]
    minio = values["HOST_MINIO_API_PORT"]
    ollama = values["HOST_OLLAMA_PORT"]
    tts = values["HOST_TTS_PORT"]
    grafana = values["HOST_GRAFANA_PORT"]
    prometheus = values["HOST_PROMETHEUS_PORT"]
    jaeger = values["HOST_JAEGER_UI_PORT"]
    loki = values["HOST_LOKI_PORT"]
    lines = [
        "# Generated by scripts/dev/ensure_ports.py. Delete this file or run",
        "# `scripts/dev/ensure_ports.py --refresh` to allocate a new set.",
    ]
    for key in PORTS:
        lines.append(f"{key}={values[key]}")
    lines.extend(
        [
            f"PUBLIC_BASE_URL=http://localhost:{web}",
            f"WEB_URL=http://localhost:{web}",
            f"API_URL=http://localhost:{api}",
            f"BROWSER_RUNTIME_URL=http://localhost:{browser}",
            f"AGENT_RUNTIME_URL=http://localhost:{agent}",
            f"MINIO_URL=http://localhost:{minio}",
            f"OLLAMA_URL=http://localhost:{ollama}",
            f"TTS_URL=http://localhost:{tts}",
            f"NEXT_PUBLIC_API_BASE_URL=http://localhost:{api}",
            f"NEXT_PUBLIC_EVENTS_BASE_URL=http://localhost:{api}",
            f"NEXT_PUBLIC_BROWSER_RUNTIME_URL=http://localhost:{browser}",
            f"NEXT_PUBLIC_AGENT_RUNTIME_URL=http://localhost:{agent}",
            f"NEXT_PUBLIC_MINIO_URL=http://localhost:{minio}",
            f"NEXT_PUBLIC_GRAFANA_URL=http://localhost:{grafana}",
            f"NEXT_PUBLIC_PROMETHEUS_URL=http://localhost:{prometheus}",
            f"NEXT_PUBLIC_JAEGER_URL=http://localhost:{jaeger}",
            f"NEXT_PUBLIC_LOKI_URL=http://localhost:{loki}",
            "NEXT_PUBLIC_PROVIDER_MODE_LABEL='Fake Providers'",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--refresh", action="store_true", help="Ignore existing ports.env")
    args = parser.parse_args()

    if OUT_FILE.exists() and not args.refresh:
        existing = parse_env(OUT_FILE)
        required = set(PORTS) | {
            "WEB_URL",
            "API_URL",
            "OLLAMA_URL",
            "TTS_URL",
            "NEXT_PUBLIC_API_BASE_URL",
        }
        if set(PORTS).issubset(existing) and not required.issubset(existing):
            OUT_FILE.write_text(render(existing), encoding="utf-8")
            print(f"Updated local port allocation: {OUT_FILE.relative_to(ROOT)}")
            return 0
        if required.issubset(existing):
            print(f"Using existing local port allocation: {OUT_FILE.relative_to(ROOT)}")
            return 0
        print(f"Refreshing incomplete port allocation: {OUT_FILE.relative_to(ROOT)}")

    env_values = parse_env(ENV_FILE)
    allocated: set[int] = set()
    values: dict[str, str] = {}
    for key, preferred in PORTS.items():
        configured = env_values.get(key)
        if configured and configured.isdigit():
            port = int(configured)
            if port in allocated:
                raise RuntimeError(f"{key}={port} duplicates another configured port.")
            if not port_is_free(port):
                raise RuntimeError(f"{key}={port} is already in use.")
            allocated.add(port)
            values[key] = str(port)
        else:
            values[key] = str(pick_port(preferred, allocated))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(values), encoding="utf-8")
    print("Allocated local ports:")
    for key in PORTS:
        print(f"  {key}={values[key]}")
    print(f"Wrote {OUT_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
